// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfcnfsuewwnayeubronb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmY25mc3Vld3duYXlldWJyb25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTI4NjQsImV4cCI6MjA3MDI2ODg2NH0.6PUgUGlORI9V6XJmUofdNgYNprb7gJcRycbwBokml9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});